/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI_SystemAdmin;

import UI_Community_admin.CommunityAdmin;
import UI_Community_admin.CreateCommunity;
import UI_Community_admin.ViewCommunity;
import UI_Hospital_Admin.CreateHospitalDirectory;
import UI_Hospital_Admin.ViewHospitalDirectory;

/**
 *
 * @author jkoti
 */
public class SystemAdminOption extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminOption
     */
    public SystemAdminOption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        communityLable = new javax.swing.JLabel();
        systemLable = new javax.swing.JLabel();
        hospitalLable = new javax.swing.JLabel();
        viewComm = new javax.swing.JButton();
        btnEditHospital = new javax.swing.JButton();
        btnEditComm = new javax.swing.JButton();
        viewHD = new javax.swing.JButton();
        viewSystem = new javax.swing.JButton();

        jButton7.setBackground(new java.awt.Color(153, 153, 153));
        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Hospital Directory");
        jButton7.setRolloverEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        communityLable.setIcon(new javax.swing.ImageIcon("C:\\Users\\jkoti\\Downloads\\icons8-users-60.png")); // NOI18N

        systemLable.setIcon(new javax.swing.ImageIcon("C:\\Users\\jkoti\\Downloads\\icons8-system-administrator-male-64.png")); // NOI18N

        hospitalLable.setIcon(new javax.swing.ImageIcon("C:\\Users\\jkoti\\Downloads\\icons8-folder-invoices-pastel\\icons8-folder-invoices-64.png")); // NOI18N

        viewComm.setBackground(new java.awt.Color(153, 153, 153));
        viewComm.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        viewComm.setForeground(new java.awt.Color(255, 255, 255));
        viewComm.setText("Community");
        viewComm.setRolloverEnabled(false);
        viewComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCommActionPerformed(evt);
            }
        });

        btnEditHospital.setBackground(new java.awt.Color(153, 153, 153));
        btnEditHospital.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEditHospital.setForeground(new java.awt.Color(255, 255, 255));
        btnEditHospital.setText("Edit");
        btnEditHospital.setRolloverEnabled(false);
        btnEditHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditHospitalActionPerformed(evt);
            }
        });

        btnEditComm.setBackground(new java.awt.Color(153, 153, 153));
        btnEditComm.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEditComm.setForeground(new java.awt.Color(255, 255, 255));
        btnEditComm.setText("Edit");
        btnEditComm.setRolloverEnabled(false);
        btnEditComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCommActionPerformed(evt);
            }
        });

        viewHD.setBackground(new java.awt.Color(153, 153, 153));
        viewHD.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        viewHD.setForeground(new java.awt.Color(255, 255, 255));
        viewHD.setText("Hospital Directory");
        viewHD.setRolloverEnabled(false);
        viewHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHDActionPerformed(evt);
            }
        });

        viewSystem.setBackground(new java.awt.Color(153, 153, 153));
        viewSystem.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        viewSystem.setForeground(new java.awt.Color(255, 255, 255));
        viewSystem.setText("System");
        viewSystem.setRolloverEnabled(false);
        viewSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSystemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(communityLable)
                        .addComponent(hospitalLable))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(systemLable)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btnEditComm, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnEditHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewComm, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(viewHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(hospitalLable, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(communityLable, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(viewHD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditHospital)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewComm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditComm, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(systemLable, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(viewSystem)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditHospitalActionPerformed
        CreateHospitalDirectory obj=new CreateHospitalDirectory();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditHospitalActionPerformed

    private void btnEditCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCommActionPerformed
        CreateCommunity obj=new CreateCommunity();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditCommActionPerformed

    private void viewHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHDActionPerformed
        ViewHospitalDirectory obj=new ViewHospitalDirectory();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewHDActionPerformed

    private void viewCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCommActionPerformed
       CommunityAdmin obj=new CommunityAdmin();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewCommActionPerformed

    private void viewSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSystemActionPerformed
        SystemOption obj=new SystemOption();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewSystemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdminOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdminOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdminOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdminOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemAdminOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditComm;
    private javax.swing.JButton btnEditHospital;
    private javax.swing.JLabel communityLable;
    private javax.swing.JLabel hospitalLable;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel systemLable;
    private javax.swing.JButton viewComm;
    private javax.swing.JButton viewHD;
    private javax.swing.JButton viewSystem;
    // End of variables declaration//GEN-END:variables
}
